### ISSUE TITLE
Do we need to drop first diagonals?

### ISSUE THREAD

**Issue by shappiron** [cmdoret/hicreppy#3]
Hi! 
Could you clarify whether the method is sensitive to **non-deleted** zero and first diagonals of Hi-C map. I noted that they are taken into account by computing SCC. Will it give us the correct result?

Thank you in advance!

**Comment by cmdoret** [comment]
Hello @shappiron,

By non-deleted zeros, do you mean zeros that are explicitely stored in the sparse matrix inside the cool file ?
If so, it should not change anything as the matrix gets converted to COO format in both [htrain](https://github.com/cmdoret/hicreppy/blob/b4324563c327d70be82e4765856f7e4b41037072/hicreppy/hicrep.py#L81) and [scc](https://github.com/cmdoret/hicreppy/blob/b4324563c327d70be82e4765856f7e4b41037072/hicreppy/hicrep.py#L210) commands, which erases explicit zeros.

The first diagonals are taken into account, yes. Are they excluded in the original implementation ? If so, I missed that.
