### ISSUE TITLE
liftOver on .cool files

### ISSUE THREAD

**Issue by tarak77** [cmdoret/hicreppy#4]
Hi,
I am trying to use hicreppy to check reproducibility of my contact maps. It turns out that one of my .cool files was mapped to mm9 and the other was mm10. Is there a way to liftOver the coordinates of mm9 .cool file to mm10??

Any help will be great!

**Comment by cmdoret** [comment]
Hi @tarak77,

While it seems that [crossmap](http://crossmap.sourceforge.net/) can do this from the BAM filess, I would not attempt to use it in that case.
The assemblies do not have the same length, some regions are duplicated or missing in either of them.
These differences will bias your results when measuring reproducibility. It is better to generate the map anew.

**Comment by tarak77** [comment]
@cmdoret: actually, I was trying to compare my data's .cool file which is mm10, with the other published studies .cool file which is in mm9. But thank you though.

**Comment by cmdoret** [comment]
Yeah in that case it's probably better to realign the fastq to the same assembly :/

Best
