### ISSUE TITLE
Subsample option

### ISSUE THREAD

**Issue by saramanc** [cmdoret/hicreppy#7]
Hi! Thank you for develop hicreppy for the community. 

I'm testing different celltypes coming from different experimental sets and I would like to rerun making sure that all the sample have comparable number of contacts. I noticed there is already the option to subsample but could not understand from the documentation how to set this parameter. Could you please advice?
-s, --subsample INTEGER  Subsample contacts from both matrices to target
                           value. Leave to 0 to disable subsampling.
                           [default: 0]

Thank you in advance!

**Comment by cmdoret** [comment]
Hi @saramanc, sure!

hicreppy should be run on raw matrices (i.e. matrices which have not been balanced / normalized).
This means that every value in the matrix is an integer representing the raw number of contacts (sry if this is obvious).

Of course, you can separately subsample your matrices before running hicreppy, in which case you don't need to use `--subsample`. This option is just a convenience function in case you don't want to store a subsampled copy of each file.

To use it, assume you have `a.cool` and `b.cool`, where `a.cool` has 2,000 contacts and b.cool has 1,000 contacts, you would simply run:
```sh
hicreppy scc --subsample 1000 [...] a.cool b.cool
```

internally, hicreppy will randomly sample 1000 contacts from each matrix before running the comparison. Does that make sense?

**Comment by saramanc** [comment]
Yes, it totally make sense! Thank you for your support.
